# App Info
ios_app_id                                : 1274112191                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://itunes.apple.com/us/app/cloudy-weather-forecast/id1274112191?mt=8 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Accurate local weather alerts - Available now on iPhone, iPad & Apple Watch.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ciprian Redinciuc                               
your_link                                 : https://applicodo.com                     
your_city                                 : Iasi                                
email_address                             : ciprian@applicodo.com
facebook_username                         : getcloudyapp                                 
instagram_username                        : 
twitter_username                          : getcloudyapp
github_username                           : applicodo
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Accurate
    description                           : Powered by DarkSky, Cloudy’s forecast precision can satisfy even the most tech-savvy users.
    fontawesome_icon_name                 : location-arrow
    
  - title                                 : Precipitation intensity
    description                           : Find out when the next rain will start with a minutely precision thanks to Cloudy’s precipitation forecast.
    fontawesome_icon_name                 : umbrella

  - title                                 : Alerts and notifications
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : exclamation-triangle

  - title                                 : Weather maps and more
    description                           : Discover Cloudy’s weather maps, Today Widget, Apple Watch counterpart, Apple Watch complications  and much more.
    fontawesome_icon_name                 : globe-americas

  - title                                 : Available now on iPhone, iPad & Apple Watch.
    description                           : Enjoy checking weather again with our feature-packed application on devices with iOS 10 or later.
    fontawesome_icon_name                 : tablet-alt
  
  - title                                 : Multiple languange support
    description                           : English, French, German, Hungarian, Italian, Portuguese, Romanian, Russian, Simplified Chinese, Spanish, Swedish, Traditional Chinese.
    fontawesome_icon_name                 : flag



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#6955e8"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#6955e8"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6955e8"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
